version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes: 
      - ./data/mysql:/var/lib/mysql
    environment: 
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chat_demo

  redis:
    image: redis
    environment: 
      - TZ=Asia/Shanghai

  etcd:
    image: bitnami/etcd:3.4.14
    environment: 
      - TZ=Asia/Shanghai
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - 2379:2379
      - 2380:2380


  zipkin:
    image: openzipkin/zipkin-slim
    ports: 
      - 9411:9411
    environment: 
      - TZ=Asia/Shanghai


  gateway:
    image: dkfbasel/hot-reload-go:1.14.2
    ports:
      - 8888:8888
    volumes:
      # mount the project into the docker container. Please note, that the
      # app directory is symlinked into the project path specified as
      # environment variable. For goconvey to work, the package must be
      # linked directly into the the package directory i.e. /go/src/[PROJECTPATH]
      - ../:/app
      - ../../micro-lite:/micro-lite
      - ../../socket-gw:/socket-gw # use local repo for developing
    environment: 
      - TZ=Asia/Shanghai
      # directory to look for the main go entry point (default: /app)
      - DIRECTORY=/app/gateway
      # specify the command that should be run, can be 'build' or 'test'
      # 'build' is the default command 
      - CMD=build
      # arguments can be used to specify arguments to pass to the executable
      # on running
      - ARGS=-registry_addrs=etcd:2379 -tracer_addr=zipkin:9411
      # ignore will indicate which subdirectories to ignore from watching
      - IGNORE=/src/web
      - GO111MODULE=on
      - GOPROXY=https://goproxy.cn,direct
    depends_on: 
      - mysql
      - redis
      - etcd
      - zipkin

  chat-srv:
    image: dkfbasel/hot-reload-go:1.14.2
    # ports:
      # - 8889:8889  # do not need to expose port, it's a internal service
    volumes:
      # mount the project into the docker container. Please note, that the
      # app directory is symlinked into the project path specified as
      # environment variable. For goconvey to work, the package must be
      # linked directly into the the package directory i.e. /go/src/[PROJECTPATH]
      - ../:/app
      - ../../micro-lite:/micro-lite # use local repo for developing
      - ../../socket-gw:/socket-gw # use local repo for developing
    environment: 
      - TZ=Asia/Shanghai
      # directory to look for the main go entry point (default: /app)
      - DIRECTORY=/app/chat-srv
      # specify the command that should be run, can be 'build' or 'test'
      # 'build' is the default command 
      - CMD=build
      # arguments can be used to specify arguments to pass to the executable
      # on running
      - ARGS=-registry_addrs=etcd:2379 -redis_addr=redis:6379 -tracer_addr=zipkin:9411
      # ignore will indicate which subdirectories to ignore from watching
      - IGNORE=/src/web
      - GO111MODULE=on
      - GOPROXY=https://goproxy.cn,direct
    depends_on: 
      - mysql
      - redis
      - etcd
      - zipkin
